sudo: false
language: ruby
cache: bundler

rvm:

  - 2.3.4

before_install: gem install bundler -v 1.17.1



env:
  global:
    - CI=true
    - TRAVIS=true

after_success:
    - CI=true TRAVIS=true coveralls --verbose