# frozen_string_literal: true

source "https://rubygems.org"

gem 'rspec', '~> 3.0'
gem 'minitest'
gem 'test-unit'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
